### ISSUE TITLE
p4 sync to specific changelist for a build

### ISSUE THREAD

**Issue by alexyanw** [p4paul/p4-jenkins#11]
Right now, the job can only poll latest or every changelist touching interested p4spec.
Is it possible to sync specific changelist to trigger a build, either passed in as job parameter or as a plugin config option?

**Comment by p4paul** [comment]
Sorry for the delay; I normally use Jenkins JIRA for issues not GitHub.

There are a few ways to build at a change: 
(1) Use the 'Build Review' button and provide a change number or label (the other fields are optional).  (2) Call the URL endpoint providing the build parameters (see Markdown for details).
(3) Use the pin at label/change in the config to always limit the change.

I'll close the issue on GitHub, please feel free to reopen on Jenkins JIRA.
