### ISSUE TITLE
Upgrade p4java to 2014.1

### ISSUE THREAD

**Issue by bdkoepke** [p4paul/p4-jenkins#12]
The current p4-jenkins plugin depends on the 2013.2 library. Is there an ETA on when the library will be updated to 2014.1? I've already successfully built the plugin using the latest version, it just isn't in maven yet.

My colleague contacted perforce directly about this and already has a stacktrace indicating issues with the older software library version: http://forums.perforce.com/index.php?/topic/3723-p4java-client-too-old-error-groovy

**Comment by p4paul** [comment]
I have been pushing here too to get P4Java in Maven.

Previously I used Jenkins own Artifactory, but there seems to be a change in policy, so I have been unable to deploy the new jar.

I tend to use Jenkins JIRA for issues.  I'll close the issue in GitHub, please feel free to reopen in JIRA.
Kind regards,
Paul
