### ISSUE TITLE
Post-build publish not support .p4ignore file

### ISSUE THREAD

**Issue by PinkyJie** [p4paul/p4-jenkins#14]
It seems post-build publish does not support .p4ignore file when submitting files back to P4.
Even I setup the Environment Variable P4IGNORE to .p4ignore in the Jenkins machine, it still does not work.
Does this plugin support this or I need to change my config to utilize .p4ignore?

**Comment by p4paul** [comment]
The plugin does not read the .p4ignore (it's a bug that I need to fix).  Please log issues on the Jenkins JIRA page and add `p4` into the 'Component/s' field:

https://issues.jenkins-ci.org/browse/JENKINS/component/19224

In the short term you might be able to use a workspace mapping to exclude a path or file for your publish step e.g.

    //depot/proj/main/... //workspace/...
    -//depot/proj/main/....bin //workspace/....bin
    -//depot/proj/main/build/... //workspace/build/...

The first line maps all of `//depot/proj/main`, line 2 excludes all `.bin` files at any depth and the last line excludes the build directory.  Please note that you should always use different workspaces for populating and publishing.

**Comment by PinkyJie** [comment]
Thanks for quick response. 
Is it possible that I use the same workspace for both populating and publishing, but use different View Mappings?

**Comment by p4paul** [comment]
A workspace can only have one view mapping and changing it in between populate/publish steps is not recommended. 

Typically I create a workspace called `jenkins-${NODE_NAME}-${JOB_NAME}` for the populate stage then a second workspace called `jenkins-${NODE_NAME}-${JOB_NAME}-publish` for the publish step.  

The publish workspace's view should be extremely narrow, only mapping the file or files I want to submit. e.g.

    //depot/artifacts/my.jar //jenkins-${NODE_NAME}-${JOB_NAME}-publish/build/libs/my.jar

**Comment by PinkyJie** [comment]
Thanks! I'll try your solution. BTW, a bug is filed on Jenkins JIRA page: https://issues.jenkins-ci.org/browse/JENKINS-31061

**Comment by p4paul** [comment]
Thanks, I'll close the issue here as I prefer to track them on the JIRA page.
