### ISSUE TITLE
Is it possible to use Credentials Parameter for Perforce Credentials?

### ISSUE THREAD

**Issue by PinkyJie** [p4paul/p4-jenkins#16]
I want to use parameter to decide which account the job is using for Pull/Push code.

**Comment by p4paul** [comment]
The basic Credentials only contains a Username and Password. The Perforce Server address was moved into the Perforce Credentials to simplify the connection, otherwise you would need to specify the Perforce Server address for each Jenkins Job.

Do you want to run the Jenkins Job as the user that submitted the change? There may be an alternative approach where the P4 Plugin has 'admin' rights and logs in as the user.

**Comment by PinkyJie** [comment]
Yes, our Jenkins job will pull code from one P4 folder and then compiled it and finally push back to another folder, I want to use different account to push the code back. I see Jenkins support Credentials Parameter feature, means when you start a build, you can specify a specific Perforce Credentials. But the current problem is it seems P4 plugin only support hard-code one Perforce Credential in job configuration.

**Comment by p4paul** [comment]
Yes currently the P4 plugin is limited to a fixed user for the task. 
My proposal is to allow user (with 'admin' Perforce permissions) to login on behalf of the user that submitted the original change. It can impersonate the user without needing the password.
It would need me to make a few changes to the code, but not impossible.  I just wanted to find out if this proposal would solve your problem.

**Comment by PinkyJie** [comment]
I see, but I'm afraid in our company developer won't have "admin" account for Perforce, it would be better if the plugin can support pass in an Perforce Credential as parameter.

**Comment by p4paul** [comment]
I understand.  You might be able to pass in the user details as a credential using the Workflow plugin.

As an alternative I could create a Perforce Credential that can read or search the standard Username/Password Credentials.  However, this would require all users to create a Credential or somehow link it to a LDAP/AD service.

**Comment by PinkyJie** [comment]
Maybe Workflow plugin is a good option. I'll try this first. Thanks!

**Comment by PinkyJie** [comment]
Hi @p4paul, I installed workflow-aggregator plugin, but I don't know how to use this to pass credential parameter to P4 Plugin. Could you show me some guide?

**Comment by p4paul** [comment]
I must admit I have not tried this out, but came across this blog:
https://www.cloudbees.com/blog/workflow-integration-credentials-binding-plugin
Perhaps this will provide a short term solution.  In the new year I'm hoping to extend the Perforce Credentials to match your requirements (perhaps by the end of January or February) .

**Comment by PinkyJie** [comment]
I check the blog, it seems the blog is using Workflow plugin to expand the credential to variables and then use these variable in script, I can achieve the same functionality using Credentials Binding Plugin. The problem is P4 plugin can not use variable to specify Perforce Credentials, so both Workflow and Credentials Binding Plugin can not work.

**Comment by p4paul** [comment]
Big thank you for checking this out.  I think the best option is to see if I can make use of the Standard User/Pass credentials.  It looks like that will solve a host of integration issues.  I'm out on vacation now until the 4th Jan, but will let you know as soon as I have an implementation to try out.

**Comment by mqw** [comment]
Hi Paul,
Is this issue going to be remedied somehow? I have found a few similar questions online and no answer on automating p4 credentials import/greation into jenkins. Or maybe there is a workaround I'm not aware of?

**Comment by p4paul** [comment]
Can I just clarify, do you want to:
1. provide a pre-existing credential parameter into the build.
2. create a new credential (for use in the build)
3. Is this for free-style jobs, pipe-line jobs or both?

**Comment by p4paul** [comment]
https://jenkins.io/doc/pipeline/steps/credentials-binding/
