### ISSUE TITLE
P4 submit failed won't make Jenkins job failed

### ISSUE THREAD

**Issue by PinkyJie** [p4paul/p4-jenkins#17]
![p4-submit-error](https://cloud.githubusercontent.com/assets/551329/12189494/23b3097e-b573-11e5-9122-0536e00ab5c5.PNG)

See attachment, the publish action is failed with error, but the Jenkins job is still success, it there a config that we can set to let Jenkins fail when publish is failed?

**Comment by p4paul** [comment]
Sorry I missed your issue, please raise them on JIRA:

https://issues.jenkins-ci.org/browse/JENKINS-33229?jql=project%20%3D%20JENKINS%20AND%20status%20in%20(Open%2C%20%22In%20Progress%22%2C%20Reopened)%20AND%20component%20%3D%20%27p4-plugin%27

It looks like a protections issue, have you checked the Perforce user defined in the credentials has the necessary 'write' permission?
