### ISSUE TITLE
Label Published Assets

### ISSUE THREAD

**Issue by mmosttler** [p4paul/p4-jenkins#18]
We always label our source that was used to build the assets as well as label the resulting assets.
I am able to label the source using the Perforce Label post build step, but can't seem to find how to label the published assets.

Is it possible to actually label the published assets using the workspace view that is specific to the publish asset step?

**Comment by p4paul** [comment]
No it is not possible to label the Published Asset (unless it was within the workspace view used to build the asset).

It would be a good feature to add; please can you log the SIR on the Jenkins JIRA pages for the component `p4` (not the old `perforce` component).

https://issues.jenkins-ci.org/browse/JENKINS-33229?jql=project%20%3D%20JENKINS%20AND%20status%20in%20(Open%2C%20%22In%20Progress%22%2C%20Reopened)%20AND%20component%20%3D%20%27p4-plugin%27

Kind regards,
Paul
