### ISSUE TITLE
ArrayIndexOutOfBoundsException when syncing from a directory inside the workspace

### ISSUE THREAD

**Issue by aWildElephant** [p4paul/p4-jenkins#20]
I am currently working on a project using the jenkins pipeline plugin. Most of files are on Git but there is still some on Perforce. I would like to sync a folder of my depot to a specific directory in my workspace. Unfortunately I don't know how to set up my perforce mapping properly so instead I cd to the directory in my workspace and sync the right path in my depot:

`dir (a/b) {
    p4sync credential: 'my-credentials', depotPath: '//depot/a/b'
}`

When I start two jobs simultaneously I get the following exception for the second job:

> java.lang.ArrayIndexOutOfBoundsException: 1
> 	at org.jenkinsci.plugins.p4.tasks.AbstractTask.setEnvironment(AbstractTask.java:109)
> 	at org.jenkinsci.plugins.p4.PerforceScm.checkout(PerforceScm.java:251)
> 	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:109)
> 	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:83)
> 	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:73)
> 	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:49)
> 	at hudson.security.ACL.impersonate(ACL.java:213)
> 	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:47)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
> 	at java.lang.Thread.run(Thread.java:744)

There is indeed an ominous "parts[1]" in AbstractTask#setEnvironment. I am guessing that buildWorkspace is not the workspace but the current directory, so buildWorkspace.getName() will not contain the "@" character, even though the full path we get using buildWorkspace.getRemote() has it.

Am I using the plugin properly? And regardless of my use of the plugin, do you think this is worth a patch?

**Comment by p4paul** [comment]
I had not considered the use of dir().  The Jenkins workspace and Perforce workspace should really be at the same path.  

Perforce has an advanced mapping option you can define in the 'View' field in the Workspace Spec.  You can use it by accessing the class directly and using the Groovy 'checkout' function.

For example, if your code is in `//depot/project/...` and you want it in a subdirectory called `stuff/` under your workspace (assuming your Perforce workspace root and Jenkins workspace root are at the same level):

    //depot/project/... //WORKSPACE_NAME/stuff/...

Jenkins also uses variable expansion, which is supported in the view mapping.  So typically I use 'jenkins-${NODE_NAME}-${JOB_NAME}' for a Perforce workspace name; this would give a view mapping of:

    //depot/project/... //jenkins-${NODE_NAME}-${JOB_NAME}/stuff/...

Here is a Groovy snippet:

````
checkout([$class: 'PerforceScm', 
	credential: 'phooey1666', 
	populate: [$class: 'AutoCleanImpl', 
		delete: true, 
		modtime: false, 
		pin: '', 
		quiet: true, 
		replace: true], 
	workspace: [$class: 'ManualWorkspaceImpl', 
		charset: 'none', 
		name: 'jenkins-${NODE_NAME}-${JOB_NAME}', 
		pinHost: false, 
		spec: [
			allwrite: false, 
			clobber: false, 
			compress: false, 
			line: 'LOCAL', 
			locked: false, 
			modtime: false, 
			rmdir: false, 
			streamName: '', 
			view: '//depot/project/... //jenkins-${NODE_NAME}-${JOB_NAME}/stuff/...'
		]
	]
])
````

**Comment by aWildElephant** [comment]
This is exactly what I was looking for :)

> I had not considered the use of dir().
You're probably right, the dir() felt like a dirty fix anyway. Thank you for the detailed answer.
