### ISSUE TITLE
javadoc issues

### ISSUE THREAD

**Issue by atiniir** [p4paul/p4-jenkins#21]
i've had to disable javadoc generation for the fork at jenkinsci/p4-plugin is this a known issue? 

Also what's the best way to raise issues or questions for jenkinsci/p4-plugin? the issues there seem to be disabled.

**Comment by p4paul** [comment]
You may need a JIRA account, but you should be able to raise issues here:

   http://issues.jenkins-ci.org/secure/IssueNavigator.jspa?mode=hide&reset=true&jqlQuery=project+%3D+JENKINS+AND+status+in+%28Open%2C+%22In+Progress%22%2C+Reopened%29+AND+component+%3D+%27p4-plugin%27

The link is from the Jenkins Wiki page on the 'Open Issue' link:

   https://wiki.jenkins-ci.org/display/JENKINS/P4+Plugin

As for the Javadoc generation; I don't see this as I build with Java 7, but I have seen some reported issues with Java 8.

**Comment by atiniir** [comment]
great thanks for the reply! i'll submit issues on the jenkins jira site you linked.

**Comment by p4paul** [comment]
Javadoc issues should now be fixed.
