### ISSUE TITLE
ClientHelper constructor breaking change introduced in 1.3.6

### ISSUE THREAD

**Issue by D-Hartley** [p4paul/p4-jenkins#26]
I am currently having an issue with the Artifactory plugin for Jenkins. It has been developed to work with the P4 plugin version 1.3.3. But since 1.3.6 the constructor for ClientHelper has changed from

public ClientHelper(String credential, TaskListener listener, String client)

to

public ClientHelper(String credential, TaskListener listener, String client, String charset)

which is causing an exception to be thrown.

**Comment by p4paul** [comment]
Hi David, the p4paul/p4-jenkins is an old dev line.  Active development in on [jenkinsci/p4-plugin](https://github.com/jenkinsci/p4-plugin).

Thanks for letting me know about the Artifactory plugin, I'll add the old constructor back and mark it as @Deprecated (I'll have to assume no charset or default to UFT8).

**Comment by D-Hartley** [comment]
Thanks for the fix
I'll add to JIRA in future
