### ISSUE TITLE
p4 publish does not work in declarative Jenkins Pipeline

### ISSUE THREAD

**Issue by SonamChakravarti** [p4paul/p4-jenkins#30]
`stage('Publish Assets')
{
 when{
  expression {
   //some condition
   }
 }
 steps{
 p4publish(credential: 'abcd', publish: [$class: 'SubmitImpl', delete: false, description: 'Submitted by Jenkins. Build: ${BUILD_TAG}', onlyOnSuccess: true, purge: '', reopen: false], workspace: [$class: 'ManualWorkspaceImpl', charset: 'none', name: 'jenkins-abcd-publish', pinHost: false, spec: [allwrite: true, backup: false, clobber: false, compress: false, line: 'LOCAL', locked: false, modtime: false, rmdir: false, serverID: '', streamName: '//abcd/efg', type: 'WRITABLE', view: '']])
 }
}`

I tried a couple of things and placing it under script block as well but no luck. There is no error in the logs. Is it not suppose to work with declarative pipelines or am I missing something? It would be nice if I could get some help on this

**Comment by SonamChakravarti** [comment]
Figured out the issue. In declarative pipelines, the parameters cannot be access using ${} notation. They need to be params.ParameterName within the steps block

**Comment by p4paul** [comment]
Thank you for posting back, sorry I didn't reply sooner.  I don't check here very often, please raise your issues in [jenkinsci/p4-plugin](https://github.com/jenkinsci/p4-plugin) or in Jenkins [JIRA](issues.jenkins-ci.org). 
Thanks, 
Paul
