### ISSUE TITLE
ChangeView ignored

### ISSUE THREAD

**Issue by congeal** [p4paul/p4-jenkins#31]
First of all, I appreciate your work. Thanks to you, I could set up Jenkins projects using Perforce.

Anyway, I want to populate specific reversion of some files when I checkout.
To do this, I passed changeView attribute including depots with a revision number when I called clientSpec but it was ignored.
I have found the comment below from the source code:
'// TODO (p4java 17.2) changeView'
Does it mean changeView hasn't yet implemented?
Then, do you have a plan to implement this feature?

**Comment by p4paul** [comment]
Thank you for getting in touch; I don't use this branch very often, if you need to fork or raise a pull request please use jenkinsci/p4-plugin.

Thanks for the reminder - I was waiting for p4java 17.2 support.  I had added the TODO to remind me, guess that didn't work ;-)

**Comment by p4paul** [comment]
ChangeView did not make it into p4java 17.2 - we might target this for 17.3, then I can add it to the p4-plugin.

**Comment by congeal** [comment]
@p4paul Thank you for reply.
I’ll wait for p4jave 17.3.
