### ISSUE TITLE
utf8 issue

### ISSUE THREAD

**Issue by jgarvock2** [p4paul/p4-jenkins#32]
Using P4 Plugin 1.7.3
Cloudbees Jenkins Enterprise 2.73.1.2-rolling

The sync behavior is different between the P4 Plugin and p4.exe / P4V.
Some files in my branch are of type utf8. 
Syncing from a Unix P4 server to Windows client is adding a BOM entry.
This is only happening when using the P4 Plugin.
Doing a force sync on the problem files using p4.exe removes the extra BOM entry.

The current workaround that works is to add “-Dcom.perforce.p4java.filesys.utf8bom=0” to the Jenkins slave JVM arguments.

**Comment by p4paul** [comment]
Thank you for getting in touch; I don't use this branch very often, if you need to fork or raise a pull request please use jenkinsci/p4-plugin and use issues.jenkins-ci.org for issues.

The FILESYS_UTF8BOM_SHORT_FORM property was added to p4java in 17.2.1520188 and the p4 plugin 1.7.3 includes a newer version, but it looks like I forgot to set it to 0 (default is 1).
