### ISSUE TITLE
[Question] Multibranch Pipeline View Mappings

### ISSUE THREAD

**Issue by bingshiao** [p4paul/p4-jenkins#34]
Does View Mappings field in Multibranch Pipeline job support exclusion (-) and overlay (+) syntax as describe in https://www.perforce.com/perforce/doc.current/manuals/cmdref/index.html#CmdRef/views.html#Usage_Notes%3FTocPath%3DViews%7C_____1

I'm trying to do:
```
...
-myCache\...
+myLibrary\...
```

but does not seem to be working.

**Comment by p4paul** [comment]
Please can you email support@perforce.com; as they can help look at your specific case.  

If you want to raise an issue in the community please use issues.jenkins-ci.org and set 'p4' as the component (not 'perforce' as that is the old plugin).

If you want to submit a pull request please use https://github.com/jenkinsci/p4-plugin as p4paul/p4-jenkins is my dev branch and often out of date.

What type of MultiBranch configuration are you using 'HelixBranches' 'HelixStreams' etc...?

Are you referring to the 'Include streams' in the Streams MultiBranch configuration?  This does not support inclusionary or exclusionary mappings. 

I will close this issue, but please raise the support ticket and feel free to CC me, my Perforce user id/email is 'pallen'.
