### ISSUE TITLE
Helix branches do not recurse when defining multibranch pipeline

### ISSUE THREAD

**Issue by pollockm** [p4paul/p4-jenkins#37]
If I have a multibranch pipeline and set Helix Branch as the source, and provide it with //depot/… as my branch to include, it only seems to scan one layer deep (it picks up //depot/project/Jenksinfile , but does not pick up //depot/project/dev/username/Jenkinsfile).

The help tip for this input claims that "A List of Perforce Depot paths (separated by new lines). The plugin will recursively search for a Jenkinsfile (or defined item) using the last directory name for the multi-branch name."  

This does not seem to be true.

I can trick it by defining separate entries for each depth of hierarchy I might expect:

//depot/\*
//depot/\*/\*
//depot/\*/\*/\*
etc

I care about this because I want to use a single job definition for all of my client projects, each of which is free to use a Jenkinsfile of their choosing, to reduce maintenance.  Not all projects follow an identical depth of hierarchy.

Using P4 plugin 1.8.12.

**Comment by p4paul** [comment]
Closing Issue; moved to: https://issues.jenkins-ci.org/browse/JENKINS-52605
