### ISSUE TITLE
Unable to use perforce tickets set by jenkins to automate perforce login

### ISSUE THREAD

**Issue by 01pooja** [p4paul/p4-jenkins#42]
Trying to automate login in jenkins as passsword expires after few days. Jenkins sets $P4_TICKET environment variable. I am trying to use this so that user need not to relogin again to enter his password.

echo $P4_TICKET | sudo dd conv=notrunc oflag=append of=/home/.p4tickets
cat $HOME/.p4tickets
export P4TICKETS=/home/.p4tickets

Actual result : Unexpected exception while loading target: Perforce password (P4PASSWD) invalid or unset.

**Comment by p4paul** [comment]
For future please raise issues on the Jenkins JIRA site issues.jenkins-ci.org or if you have a support account email support@perforce.com.

It looks like you need to create a long lived ticket please see this guide (steps 1 to 4, you don't need the other steps): https://community.perforce.com/s/article/2589

The run a `p4 login -p` or `p4 login -ap` for all hosts.  Copy the ticket value and paste it into the Jenkins  Perforce Ticket Credential (see guide https://github.com/jenkinsci/p4-plugin/blob/master/docs/CREDENTIALS.md#add-a-perforce-ticket-credential)

**Comment by 01pooja** [comment]
Thank you for the comments.

**Comment by 01pooja** [comment]
`p4 login -p` and `p4 login -ap` requires password to be entered. But in jenkins i am trying to automate login by using P4_TICKET set by jenkins. Anyways we ask in the other forum.

Thank you
