### ISSUE TITLE
Polling not working, Polling Log JS not working

### ISSUE THREAD

**Issue by haferburg** [p4paul/p4-jenkins#44]
I enabled "Poll SCM", and I can see that Jenkins is regularly performing the check. There is a new CL in the workspace, but the build isn't triggered.

The "Perforce Software Polling Log" says 

    p4 changes -m20 //jenkins-PerforceTest_trunk/...@419723,now

and P4V show that there is a newer CL 419745.

In the polling log the Javascript `+` toggles don't work, e. g.  `javascript:toggle('p4content0','p4title0');`. Nothing happens when I click on them. I tried in FF and Chrome. These links work fine in the `/consoleFull` log, the HTML also looks identical. To me it looks like some script includes are missing, or whatever that's called in webdev speak.

In the [Build Triggers](https://github.com/jenkinsci/p4-plugin/blob/master/docs/SETUP.md#build-triggers) docs it says under caveats multiple things that I don't understand.

> You must use workspaces named using the recommended environment variables, see Variable Expansion.

Why? My workspace name is `jenkins-${JOB_NAME}`, because there's only one node with only one executor.

> Do not use parameterized builds.

I don't think I do. Where do I see that?

> If you enable Poll SCM, ensure that your Auto build filters are configured to suit regular builds.

I don't have any filter set up. What I would expect the Jenkins plugin to do is trigger the build if there are any changes in the depot paths listed in the client workspace view definition. Is that not the case?

The Perforce server currently sits in a different domain than the Jenkins server, so triggers are not an option, unfortunately.

Remark: Maybe put https://github.com/jenkinsci/p4-plugin/blob/master/docs/SETUP.md#polling-build-filters after https://github.com/jenkinsci/p4-plugin/blob/master/docs/SETUP.md#build-triggers .

**Comment by kwirth2** [comment]
Hi Andreas,
I have sent you a direct email to start troubleshooting this problem.
Regards,
Karl

**Comment by haferburg** [comment]
Problem was that the job was parametrized, and one parameter was used in the client view definition, which was erroneously expanded to an empty string instead of the default value.

**Comment by p4paul** [comment]
Thank you for closing this and letting me know the outcome. 
(If you need to raise an issue in the future please can you create a JIRA on issues.jenkins-ci.org using the component `p4-plugin`.)
