### ISSUE TITLE
workspace template root=null should not be set to value in new workspaces

### ISSUE THREAD

**Issue by shaishap** [p4paul/p4-jenkins#46]
**Root: null** is a special usecase in P4 in Windows, allowing p4 sync to span multiple drives.

When used in template, newly created workspaces should keep the "null" value (and not be overwrite with local workspace folder i.e. c:\workspace).

In such cases, p4 sync command should use "...@" and not "c:\workspace@" 

changing it to "Root: c:\workspace" fails the sync

> i.e. template:
> Client:	my-client-host
> Owner:	wksp-owner
> Root:	null
> View:
> 	//depo1/A/... //my-client-host/d:/A-depofiles/...
> 	//depo1/B/... //my-client-host/e:/B-depofiles/...

**p4 sync ...@head**
Will sync depo1/A files to drive d: and depo1/B files to drive e:
Changing to **Root: c:\workspace** in the view, and running **p4 sync c:\workspace@head** will fail the sync

**Comment by p4paul** [comment]
Hi Shai, 

Please can you raise this issue on https://issues.jenkins-ci.org with component `p4-plugin` or if you prefer contact support@perforce.com and they will assist you. For pull requests please use https://github.com/jenkinsci/p4-plugin as this is my development fork (and often out of date).

For reference the p4-plugin was designed to let Jenkins determine the workspace root as the job could be executed on any number of different slaves with different roots.  This is further complicated with concurrent execution; when Jenkins builds the same job in parallel and requires a different root - normally appended with `@2`.

Kind regards,
Paul
